label monika_exclusive_1:
    scene bg club_day
    with wipeleft_scene
    "I end up waiting around for Monika and Sayori since to finish their chat and then approach them. I know those two best right now. Maybe I'll talk to Natsuki or Yuri tomorrow."
    return
    
label monika_exclusive_2:
    scene bg club_day
    with wipeleft_scene
    "I end up waiting around for Monika and Sayori since to finish their chat and then approach them. I know those two best right now. Maybe I'll talk to Natsuki or Yuri tomorrow."
    return
    
label monika_exclusive_ch3:
    "I decide to go over and ask Monika about music."
    mc "Hey Monika, you said earlier that you had taken up the harp?"
    m "Ah..."
    m "Yes, that's right."
    mc "I didn't know you were talented in that way too."
    mc "Do you play any other instruments or sing?"
    m "Well I used to play the piano for a while."
    m "And I do since for people really important to me."
    mc "Used to?"
    mc "Do you not anymore?"
    m "Well, I thought a small change in my life might make things a bit better."
    m "I'm sorry if it screws anything up."
    mc "Screws anything up?"
    mc "I think it's really cool that you're talented enough to play multiple different instruments."
    mc "Why did you want to change though?"
    mc "Isn't learning a new instrument really tough."
    m "I mean..."
    m "It's amazing what you can do with a keyboard."
    m "But sometimes not touching one can be more cathartic."
    mc "I think I see."
    mc "You mentioned you liked the feeling of it on your fingers."
    mc "Right?"
    m "Yup!"
    mc "But isn't it a little bit painful?"
    mc "I've heard you can get blisters from string instruments."
    m "Well, I think that's part of the fun."
    m "Part of the rush of it all."
    m "Maybe that's the reason why Yuri..."
    mc "Huh?"
    mc "What's that about Yuri?"
    m "Never mind I said anything."
    m "She's a wonderful girl and she'd be lucky if you chose her."
    mc "Ch-ch-chose?"
    mc "Who said anything about me choosing someone?"
    m "Come on."
    m "We both know how this ends."
    m "Boy joins club."
    m "Boy finds out club is full of cute girls."
    m "Boy chooses one and confesses to her."
    m "Girl accepts the guys feelings."
    m "Meanwhile the other girls feel slightly left out."
    m "Maybe drifting away a little."
    mc "That sounds like one of those romance game scenarios."
    m "Well what do you think you're in?"
    mc "Uh..."
    mc "I mean..."
    mc "I don't even know what a confession sounds like."
    mc "I've never confessed or been confessed to."
    m "You mean you've never had someone turn to you."
    m "Reach out and tenderly hold your hand."
    "Monika demonstrates by grabbing and holding my hand."
    "Our fingers lock as she demonstrates."
    m "Have them turn to you."
    m "Look you in the eyes."
    "I stare deep into Monika's eyes."
    "Despite her poem yesterday, her eyes don't appear burnt at all."
    "More of, a brilliant shimmering emerald."
    m "Then say,"
    m "I love you."
    "There is a long awkward pause before Monika pulls away."
    "I'm not certain which one of us is blushing more right now."
    m "Anyways"
    m "I wouldn't blame you."
    m "A lot of people who never get to experience those things find other ways to do it."
    mc "Like a romance story?"
    m "Exactly."
    m "Just because someone is on a computer screen doesn't mean they're not real."
    m "Or real to you at least."
    mc "Heh"
    mc "You almost sound like you play them."
    m "You could say I have some experience with them."
    m "But never as someone who plays them."
    m "More of..."
    m "A writer."
    mc "That makes sense then."
    m "Hmm?"
    mc "Of why you're in charge of the literature club."
    mc "If you already are a writer."
    mc "Then it would only make sense."
    m "I guess that's one way to look at it."
    m "Speaking of writing, did you remember to write your poem today."